plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:astro/recommended
  - plugin:@typescript-eslint/recommended
rules:
  '@typescript-eslint/triple-slash-reference':
    - 'error'
    - path: 'always' # MEMO: .astroのd.tsを読み込むとerrorになるのでpathをalwaysにする
overrides:
  - files:
      - '*.astro'
    parser: 'astro-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - '.astro'
    rules:
      'astro/no-conflict-set-directives': 'error'
      'astro/no-unused-define-vars-in-style': 'error'
      '@typescript-eslint/no-unused-vars': 'off'
